config/routes.php
<?php

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;

//Router::defaultRouteClass('DashedRoute');
Router::defaultRouteClass('InflectedRoute');

Router::scope('/:slug/', function (RouteBuilder $routes) {

    $routes->connect('/rastreio-rapido/*',              ['controller' => 'Pages', 'action' => 'rastreio_rapido']);

    //Nova loja
    $routes->connect('/pesquisa/*',                     ['controller' => 'Produtos', 'action' => 'busca']);
    $routes->connect('/similares/*',                    ['controller' => 'Produtos', 'action' => 'similares']);
    $routes->connect('/produtos/atualizar-produtos/*',  ['controller' => 'Produtos', 'action' => 'atualizar_produtos']);
    $routes->connect('/produtos/filtrar/*',             ['controller' => 'Produtos', 'action' => 'filtrar']);
    $routes->connect('/produtos/comprar/*',             ['controller' => 'Produtos', 'action' => 'comprar']);
    

    $routes->connect('/comparador/completo/*',          ['controller' => 'Pages', 'action' => 'comparacao_completa']);

    /*$routes->connect('/',                             ['controller' => 'Pages', 'action' => 'new_home']);
    $routes->connect('/saiba-mais/*',                   ['controller' => 'Pages', 'action' => 'new_home2']);
    $routes->connect('/home/*',                         ['controller' => 'Pages', 'action' => 'home']);*/

    $routes->connect('/',                               ['controller' => 'Pages', 'action' => 'home']);
    $routes->connect('/home/*',                         ['controller' => 'Pages', 'action' => 'home']);
    $routes->connect('/iuguwebhooks/*',                 ['controller' => 'Pages', 'action' => 'iuguwebhooks']);
    $routes->connect('/iugu_subconta_verifica/*',       ['controller' => 'Pages', 'action' => 'iugu_subconta_verifica']);
    $routes->connect('/calculadora/*',                  ['controller' => 'Pages', 'action' => 'calculadora_log']);
    $routes->connect('/calculadora-envio/*',            ['controller' => 'Pages', 'action' => 'calculadora_envio']);
    $routes->connect('/mochila/pagamento/*',            ['controller' => 'Produtos', 'action' => 'carrinho_pagamento']);
    //$routes->connect('/academia-*/',                  ['controller' => 'Pages', 'action' => 'home']);
    $routes->connect('/pages/*',                        ['controller' => 'Pages', 'action' => 'display']);
    
    $routes->connect('/promocoes/atualizar-produtos/*', ['controller' => 'Produtos', 'action' => 'promocoes_atualizar_produtos']);

    // CATALOGO DE Produtos
    $routes->connect('/catalogo/',                  ['controller' => 'Produtos', 'action' => 'catalogo']);
    $routes->connect('/catalogo/atualizar-produtos/*', ['controller' => 'Produtos', 'action' => 'catalogo_atualizar_produtos']);
    $routes->connect('/montar-catalogo/',           ['controller' => 'Produtos', 'action' => 'montar_catalogo']);
    $routes->connect('/catalogo/preview',           ['controller' => 'Produtos', 'action' => 'catalogo_preview']);
    $routes->connect('/catalogo/preview2',          ['controller' => 'Produtos', 'action' => 'catalogo_preview_2']);
    $routes->connect('/teste_preview',              ['controller' => 'Produtos', 'action' => 'teste_preview']);

    // COMBO DE Produtos
    $routes->connect('/montar-combo/*',             ['controller' => 'Produtos', 'action' => 'montar_combo']);
    $routes->connect('/atualizar-produtos-combo/*', ['controller' => 'Produtos', 'action' => 'montar_combo_atualizar_produtos']);
    $routes->connect('/combo/produto/*',            ['controller' => 'Produtos', 'action' => 'view_combo']);
    $routes->connect('/selecionar-combo/*',         ['controller' => 'Produtos', 'action' => 'selecionar_tipo_combo']);
    $routes->connect('/salvar-combo/*',             ['controller' => 'Produtos', 'action' => 'salvar_combo']);
    $routes->connect('/fechar-combo/*',             ['controller' => 'Produtos', 'action' => 'fechar_combo']);


    /**
     * ADMIN ACADEMIA
     */

    $routes->connect('/academia-ajax/*',            ['controller' => 'Academias', 'action' => 'view_ajax']);
    
    /**
     * ACADEMIA MENSALIDADE
     */
    $routes->connect('/mensalidade/*',              ['controller' => 'Academias', 'action' => 'mensalidade']);
    $routes->connect('/mensalidades/',              ['controller' => 'Academias', 'action' => 'mensalidade']);
    $routes->connect('/mensalidade/comprar/*',      ['controller' => 'Academias', 'action' => 'mensalidade_comprar']);
    $routes->connect('/mensalidade/finalizado/*',   ['controller' => 'Academias', 'action' => 'mensalidade_finalizado']);


    //Allan
    $routes->connect('/solucionar_problemas',       ['controller' => 'Pages', 'action' => 'solucionar_problemas']);
    $routes->connect('/teste_allan',                ['controller' => 'Pages', 'action' => 'teste_default']);

    $routes->connect('/promocoes/*',                ['controller' => 'Produtos', 'action' => 'promocoes']);
    $routes->connect('/mais-vendidos/',             ['controller' => 'Produtos', 'action' => 'mais_vendidos']);
    


    $routes->connect('/academias/busca-cidade/*',    ['controller' => 'Academias', 'action' => 'ajax_options']);
    $routes->connect('/academias/busca-professor/*', ['controller' => 'Academias', 'action' => 'busca_professor']);

    $routes->connect('/atletas/',                   ['controller' => 'Atletas', 'action' => 'index']);

    $routes->connect('/transportadoras',            ['controller' => 'Transportadoras', 'action' => 'index']);
    $routes->connect('/central-de-relacionamento',  ['controller' => 'RelacionamentoContatos', 'action' => 'index']);
    $routes->connect('/seja-um-parceiro',           ['controller' => 'Fornecedores', 'action' => 'index']);

    $routes->connect('/produtos/atualizar-produtos-express/*', ['controller' => 'Produtos', 'action' => 'atualizar_produtos_express']);
    $routes->connect('/produtos/atualizar-produtos-indicacao/*', ['controller' => 'Produtos', 'action' => 'atualizar_produtos_indicacao']);

    $routes->connect('/produtos/overlay-indicar-produtos/*', ['controller' => 'Produtos', 'action' => 'overlay_indicar_produtos']);
    $routes->connect('/produtos/overlay-indicar-produtos-home/*', ['controller' => 'Produtos', 'action' => 'overlay_indicar_produtos_home']);
    $routes->connect('/produtos/produto-acabou/*', ['controller' => 'Produtos', 'action' => 'produto_acabou']);
    $routes->connect('/produtos/busca/*',                       ['controller' => 'Produtos', 'action' => 'search']);
    $routes->connect('/produtos/filtro-objetivo-categoria/*',   ['controller' => 'Produtos', 'action' => 'filter_objetivo_categoria']);
    $routes->connect('/produtos/busca-completa/*',   ['controller' => 'Produtos', 'action' => 'search_completo']);
    $routes->connect('/produtos/busca-professor/*',   ['controller' => 'Produtos', 'action' => 'search_professor']);
    $routes->connect('/produtos/busca-express/*',   ['controller' => 'Produtos', 'action' => 'search_express']);
    $routes->connect('/produtos/filtro-marca/*',                ['controller' => 'Produtos', 'action' => 'filter_marca']);

    $routes->connect('/promocao/*',                 ['controller' => 'Produtos', 'action' => 'view_promo']);
    $routes->connect('/produtos/comprar/*',         ['controller' => 'Produtos', 'action' => 'comprar']);
    $routes->connect('/produtos/comprar_ind/*',     ['controller' => 'Produtos', 'action' => 'comprar_ind']);
    $routes->connect('/produtos/comprar_express/*',             ['controller' => 'Produtos', 'action' => 'comprar_express']);
    $routes->connect('/produtos/comprar_indicar/*', ['controller' => 'Produtos', 'action' => 'comprar_indicar']);
    $routes->connect('/produto/*',                  ['controller' => 'Produtos', 'action' => 'view']);
    $routes->connect('/academia-*/produto/*',                  ['controller' => 'Produtos', 'action' => 'view']);

    $routes->connect('/mochila/checar-estoque/*',   ['controller' => 'Produtos', 'action' => 'carrinho_estoque']);
    $routes->connect('/mochila/alterar/*',          ['controller' => 'Produtos', 'action' => 'carrinho_edit']);
    $routes->connect('/mochila/fechar-o-ziper/*',   ['controller' => 'Produtos', 'action' => 'carrinho_identifica']);
    $routes->connect('/mochila/usuario-preencher-dados/*', ['controller' => 'Produtos', 'action' => 'carrinho_preencher_dados']);
    $routes->connect('/mochila/pagamento/*',        ['controller' => 'Produtos', 'action' => 'carrinho_pagamento']);
    $routes->connect('/mochila/checkout/*',         ['controller' => 'Produtos', 'action' => 'carrinho_checkout']);
    $routes->connect('/mochila/finalizado/*',       ['controller' => 'Produtos', 'action' => 'carrinho_finalizado']);
    $routes->connect('/mochila/finalizado-express/*',['controller' => 'Produtos', 'action' => 'carrinho_finalizado_express']);

    $routes->connect('/log_express_pagamento/*',['controller' => 'Produtos', 'action' => 'log_express_pagamento']);

    $routes->connect('/login/esqueci-a-senha/*',        ['controller' => 'Clientes', 'action' => 'forgot_passwd']);
    $routes->connect('/login/recuperar-a-senha/*',      ['controller' => 'Clientes', 'action' => 'recover_passwd']);
    $routes->connect('/fb-login/next/*',                ['controller' => 'Clientes', 'action' => 'fb_login_callback']);
    $routes->connect('/fb-login/*',                     ['controller' => 'Clientes', 'action' => 'fb_login']);
    $routes->connect('/login/*',                        ['controller' => 'Clientes', 'action' => 'login']);
    $routes->connect('/logout/*',                       ['controller' => 'Clientes', 'action' => 'logout']);
    $routes->connect('/minha-conta/dados-faturamento',  ['controller' => 'Clientes', 'action' => 'view_dados']);
    $routes->connect('/minha-conta/meus-dados',         ['controller' => 'Clientes', 'action' => 'view_meus_dados']);

src/Model/Table/PreOrdersTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * PreOrders Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Professores
 * @property \Cake\ORM\Association\BelongsTo $Academias
 * @property \Cake\ORM\Association\BelongsTo $Clientes
 * @property \Cake\ORM\Association\BelongsTo $Pedidos
 *
 * @method \App\Model\Entity\PreOrder get($primaryKey, $options = [])
 * @method \App\Model\Entity\PreOrder newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\PreOrder[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\PreOrder|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\PreOrder patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\PreOrder[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\PreOrder findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class PreOrdersTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('pre_orders');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Professores', [
            'foreignKey' => 'professor_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Academias', [
            'foreignKey' => 'academia_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Clientes', [
            'foreignKey' => 'cliente_id',
            'joinType' => 'INNER'
        ]);
        $this->belongsTo('Pedidos', [
            'foreignKey' => 'pedido_id'
        ]);
        $this->hasMany('PreOrderItems', [
            'foreignKey' => 'pre_order_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->integer('academia_id')
            ->notEmpty('id');

        $validator
            ->integer('professor_id')
            ->notEmpty('id');

        $validator
            ->integer('cliente_id')
            ->notEmpty('id');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['professor_id'], 'Professores'));
        $rules->add($rules->existsIn(['academia_id'], 'Academias'));
        $rules->add($rules->existsIn(['cliente_id'], 'Clientes'));
        $rules->add($rules->existsIn(['pedido_id'], 'Pedidos'));

        return $rules;
    }
}

src/Controller/Admin/PreOrdersController.php
<?php
namespace App\Controller\Admin;

use App\Controller\AppController;

/**
 * PreOrders Controller
 *
 * @property \App\Model\Table\PreOrdersTable $PreOrders
 */
class PreOrdersController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => [
                'Professores',
                'Academias',
                'Clientes',
                'Pedidos',
                'PreOrderItems',
                'PreOrderItems.Produtos',
                'PreOrderItems.Produtos.ProdutoBase'
            ],
            'order' => ['PreOrders.pedido_id' => 'desc', 'PreOrders.id' => 'desc']
        ];
        $preOrders = $this->paginate($this->PreOrders);

        $this->set(compact('preOrders'));
        $this->set('_serialize', ['preOrders']);
    }

    /**
     * View method
     *
     * @param string|null $id Pre Order id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $preOrder = $this->PreOrders->get($id, [
            'contain' => ['Professores', 'Academias', 'Clientes', 'Pedidos', 'PreOrderItems']
        ]);

        $this->set('preOrder', $preOrder);
        $this->set('_serialize', ['preOrder']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $preOrder = $this->PreOrders->newEntity();
        if ($this->request->is('post')) {
            $preOrder = $this->PreOrders->patchEntity($preOrder, $this->request->data);
            if ($this->PreOrders->save($preOrder)) {
                $this->Flash->success(__('The pre order has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The pre order could not be saved. Please, try again.'));
            }
        }
        $professores = $this->PreOrders->Professores->find('list', ['limit' => 200]);
        $academias = $this->PreOrders->Academias->find('list', ['limit' => 200]);
        $clientes = $this->PreOrders->Clientes->find('list', ['limit' => 200]);
        $pedidos = $this->PreOrders->Pedidos->find('list', ['limit' => 200]);
        $this->set(compact('preOrder', 'professores', 'academias', 'clientes', 'pedidos'));
        $this->set('_serialize', ['preOrder']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Pre Order id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $preOrder = $this->PreOrders->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $preOrder = $this->PreOrders->patchEntity($preOrder, $this->request->data);
            if ($this->PreOrders->save($preOrder)) {
                $this->Flash->success(__('The pre order has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The pre order could not be saved. Please, try again.'));
            }
        }
        $professores = $this->PreOrders->Professores->find('list', ['limit' => 200]);
        $academias = $this->PreOrders->Academias->find('list', ['limit' => 200]);
        $clientes = $this->PreOrders->Clientes->find('list', ['limit' => 200]);
        $pedidos = $this->PreOrders->Pedidos->find('list', ['limit' => 200]);
        $this->set(compact('preOrder', 'professores', 'academias', 'clientes', 'pedidos'));
        $this->set('_serialize', ['preOrder']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Pre Order id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $preOrder = $this->PreOrders->get($id);
        if ($this->PreOrders->delete($preOrder)) {
            $this->Flash->success(__('The pre order has been deleted.'));
        } else {
            $this->Flash->error(__('The pre order could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Admin/PreOrders/index.ctp
<?php $this->assign('title', 'Indicações de Produtos'); ?>

<div class="content-box">
    <h3 class="content-box-header bg-default">
        <?= __('Actions') ?>
        <div class="header-buttons-separator">
            <a class="icon-separator toggle-button" href="#">
                <i class="glyph-icon icon-chevron-down icon-rotate-180"></i>
            </a>
        </div>
    </h3>
    <div class="content-box-wrapper hidee">
      <?= link_button_listAcademias(__('Listar Academias'), ['controller' => 'Academias', 'action' => 'index']); ?>
        <?= link_button_listClientes(__('Listar Clientes'), ['controller' => 'Clientes', 'action' => 'index']); ?>
        <?= link_button_listPedidos(__('Listar Pedidos'), ['controller' => 'Pedidos', 'action' => 'index']); ?>    
    </div>
</div>

<div class="preOrders index">
    <table class="table table-hover">
        <thead>
        <tr>
            <th><?= $this->Paginator->sort('id') ?></th>
            <th><?= $this->Paginator->sort('professor_id') ?></th>
            <th><?= $this->Paginator->sort('academia_id') ?></th>
            <th><?= $this->Paginator->sort('cliente_id') ?></th>
            <th><?= $this->Paginator->sort('pedido_id', 'Nº Pedido') ?></th>
            <th><?= $this->Paginator->sort('created', 'Enviada') ?></th>
            <th><?= $this->Paginator->sort('modified', 'Aceita') ?></th>
            <th class="actions"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($preOrders as $preOrder): ?>
            <tr>
                <td><?= $this->Number->format($preOrder->id) ?></td>
                <td>
                    <?= $preOrder->has('professore') ? $preOrder->professore->name : '' ?>
                </td>
                <td>
                    <?= $preOrder->has('academia') ? $preOrder->academia->shortname : '' ?>
                </td>
                <td>
                    <?= $preOrder->has('cliente') ? $preOrder->cliente->name : '' ?>
                </td>
                <td>
                    <?= $preOrder->has('pedido') ? $preOrder->pedido->id : '' ?>
                </td>
                <td><?= h($preOrder->created) ?></td>
                <td>
                    <?php
                    $badge = '';
                    if(
                        $preOrder->pedido_id   >= 1 &&
                        $preOrder->modified    != $preOrder->created &&
                        date_format($preOrder->modified, 'Y-m-d') >= date('Y-m-d', strtotime('- 7 days'))
                    ){
                        $badge = '<span class="bs-badge badge-blue-alt">NOVO</span>';
                    }
                    echo $preOrder->modified != $preOrder->created ? h($preOrder->modified).' '.$badge : '-'
                    ?>
                </td>
                <td class="actions">
                    <div class="btn-group">
                        <button class="btn btn-default dropdown-toggle" data-toggle="dropdown" type="button" aria-expanded="false">
                            <i class="glyph-icon icon-navicon"></i>
                            <span class="sr-only"><?= __('Actions'); ?></span>
                        </button>
                        <ul class="dropdown-menu  pull-right" role="menu" style="left: -110px;">
                            <li>
                                <?= $this->Html->link('<i class="glyph-icon icon-search"></i>  '.__('Ver detalhes'),
                                    '#',
                                    [
                                        'data-target'=> '#dados-'.$preOrder->id,
                                        'data-toggle'=> 'modal',
                                        'escape' => false
                                    ])
                                ?>
                            </li>
                        </ul>
                    </div>

                    <div class="modal fade"
                         id="dados-<?= $preOrder->id ?>"
                         tabindex="-1" role="dialog"
                         aria-labelledby="dados-<?= $preOrder->id ?>Label"
                         aria-hidden="true">

                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">
                                        Detalhes da Indicação <strong>#<?= $preOrder->id ?></strong>
                                        <br>
                                        Aluno: <strong><?= $preOrder->cliente->name ?></strong>
                                    </h4>
                                </div>
                                <div class="modal-body">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th class="text-center">Item</th>
                                            <th class="text-center">Cód.</th>
                                            <th>Descrição</th>
                                            <th class="text-right">Quantidade</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        $i = 1;
                                        foreach ($preOrder->pre_order_items as $item):
                                            ?>
                                            <tr>
                                                <td class="text-center"><?= $i ?></td>
                                                <td class="text-center"><?= $item->produto_id ?></td>
                                                <td><?= $item->produto->produto_base->name ?></td>
                                                <td class="text-right"><?= $item->quantidade ?></td>
                                            </tr>
                                            <?php
                                            $i++;
                                        endforeach;
                                        ?>
                                        </tbody>
                                    </table>

                                </div>
                                <div class="col-md-12">
                                    <h5>
                                        <?= $preOrder->pedido_id >= 1
                                            ? 'Indicação Aceita :: <strong>Pedido #'.$preOrder->pedido_id.'</strong>'
                                            : 'Indicação ainda não aceita'
                                        ?>
                                    </h5>
                                </div>


                                <div class="modal-footer">
                                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>

        <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>